# Generated by Django 4.0 on 2022-03-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_out',
            name='exam_status',
        ),
        migrations.AddField(
            model_name='time_out',
            name='qu_status',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='time_out',
            name='re_status',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='time_out',
            name='te_status',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='time_out',
            name='ve_status',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
