# Generated by Django 4.0 on 2022-03-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_time_out_exam_status_time_out_qu_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_out',
            old_name='re_status',
            new_name='exam_status',
        ),
        migrations.RemoveField(
            model_name='time_out',
            name='qu_status',
        ),
        migrations.RemoveField(
            model_name='time_out',
            name='te_status',
        ),
        migrations.RemoveField(
            model_name='time_out',
            name='ve_status',
        ),
    ]
