# Generated by Django 4.0.3 on 2022-04-14 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_re_status_time_out_exam_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='reference',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refer', to='app.login'),
        ),
    ]
