# Generated by Django 4.0.3 on 2022-04-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_candidates_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='reference',
            new_name='reference_id',
        ),
    ]
