# Generated by Django 4.0 on 2022-04-16 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_reference_candidates_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='reference_id',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refer', to='app.login'),
        ),
    ]
